server:
  port: 8089
  server:
      path: /
spring:
#:数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: root
    password: root
    initialization-mode: ALWAYS
#:使用Druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource

#    ==========数据源其他配置==========
#    初始化数量
    initialSize: 5
#    允许的最小空闲连接数
    minIdle: 5
#    最大活跃数
    maxActive: 20
#    最大连接等待超时时间，单位是毫秒(ms)
    maxWait: 60000
#    配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
#    配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
#    验证数据库连接的查询语句，这个查询语句必须是至少返回一条数据的SELECT语句
    validationQuery: SELECT 1
#    建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
#    申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
#    归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
#    是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
#    配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
#    合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
#    通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#:缓存数据库
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
#:mybatis
mybatis:
  type-aliases-package: com.zcf.universe.pojo
#:分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  reasonable: true
  params:
    count: countSql
logging:
  level:
    com.zcf.universe.mapper : debug #:打印SQL语句
    io.swagger.models.parameters.AbstractSerializableParameter: error #:为了解决swagger日志无端的报错
